inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4

Naming/FileName:
 Exclude:
   - lib/rubocop-solidus.rb

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'

Metrics/ClassLength:
  Exclude:
    - 'tasks/**/*.rb'

# Prevents Ruby 3.1 incompatibility error. You can enable this cop when Ruby 2.4 support is dropped.
# See https://github.com/rubocop/rubocop/issues/10258
Layout/BlockAlignment:
  Enabled: false
