# frozen_string_literal: true

require_relative 'mixin/target_solidus_version'

require_relative 'solidus/class_eval_decorator'
require_relative 'solidus/reimbursement_hook_deprecated'
require_relative 'solidus/spree_calculator_free_shipping_deprecated'
require_relative 'solidus/spree_calculator_percent_per_item_deprecated'
require_relative 'solidus/spree_calculator_price_sack_deprecated'
require_relative 'solidus/spree_default_credit_card_deprecated'
require_relative 'solidus/spree_gateway_bogus_deprecated'
require_relative 'solidus/spree_icon_deprecated'
require_relative 'solidus/spree_refund_call_perform'
require_relative 'solidus/spree_t_decprecated'
